export const endpoints = {
  identity: {
    login: '/Identity/login',
    loginWithFacebook: '/Identity/LoginWithFacebook',
    register: '/Identity/register',
    authenticate: '/Identity/authenticate/:id',
  },
  events: {
    getAll: '/Event/All',
    getSingle: '/Event/:id',
    create: '/Event/Create',
    edit: '/Event/Edit/:id',
    getAllUserEvents: '/Event/User',
    attendeeOnly: '/Event/AttendeeOnly/:id',
    getAllAdmin: '/Event/All-Administration',
    delete: '/Event/Delete/:id',
    restore: '/Event/Restore/:id',
  },
  user: {
    getAll: '/User/All',
    getAllAttendee: '/User/Attendee-Users',
    delete: '/User/Delete/:id',
  },
  attendees: {
    allByEvent: '/Attendee/AllByEvent/:id',
    createNew: '/Attendee/Create',
    delete: '/Attendee/Delete/:id',
    updateStatus: '/Attendee/UpdateStatus/:id',
    updateExternalStatus: '/Attendee/UpdateExternalStatus/:id',
    status: '/Attendee/ExternalStatus/:id',
  },
  categories: {
    getAll: '/Category/All',
    update: '/Category/Edit',
    delete: '/Category/Delete/:id',
    add: '/Category/Add',
  },
  notifications: {
    unreadCount: '/Notification/UnreadCount',
    getAll: '/Notification/All',
    markSingleAsReaded: '/Notification/MarkSingleAsRead/:id',
    delete: 'Notification/DeleteNotification/:id',
  },
  comments: {
    getAll: '/Comment/All/:id',
    create: '/Comment/Create',
    edit: '/Comment/Edit/:id',
    delete: '/Comment/Delete/:id',
  },
};
